name: extractsllc
favicon: null
layout_spectrum: 0.8545828361529857
typography_spectrum: 0.9984606732614338
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.44838130776770413
  lightness: 0.5573838038835675
  saturation: 0.5593895064666867
  rhythmicContrast: 0.9046855275519192
purpose: []
